// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/m-mizutani/octovy/pkg/infra/ent/authstatecache"
	"github.com/m-mizutani/octovy/pkg/infra/ent/predicate"
)

// AuthStateCacheQuery is the builder for querying AuthStateCache entities.
type AuthStateCacheQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.AuthStateCache
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AuthStateCacheQuery builder.
func (ascq *AuthStateCacheQuery) Where(ps ...predicate.AuthStateCache) *AuthStateCacheQuery {
	ascq.predicates = append(ascq.predicates, ps...)
	return ascq
}

// Limit adds a limit step to the query.
func (ascq *AuthStateCacheQuery) Limit(limit int) *AuthStateCacheQuery {
	ascq.limit = &limit
	return ascq
}

// Offset adds an offset step to the query.
func (ascq *AuthStateCacheQuery) Offset(offset int) *AuthStateCacheQuery {
	ascq.offset = &offset
	return ascq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ascq *AuthStateCacheQuery) Unique(unique bool) *AuthStateCacheQuery {
	ascq.unique = &unique
	return ascq
}

// Order adds an order step to the query.
func (ascq *AuthStateCacheQuery) Order(o ...OrderFunc) *AuthStateCacheQuery {
	ascq.order = append(ascq.order, o...)
	return ascq
}

// First returns the first AuthStateCache entity from the query.
// Returns a *NotFoundError when no AuthStateCache was found.
func (ascq *AuthStateCacheQuery) First(ctx context.Context) (*AuthStateCache, error) {
	nodes, err := ascq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{authstatecache.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ascq *AuthStateCacheQuery) FirstX(ctx context.Context) *AuthStateCache {
	node, err := ascq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AuthStateCache ID from the query.
// Returns a *NotFoundError when no AuthStateCache ID was found.
func (ascq *AuthStateCacheQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = ascq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{authstatecache.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ascq *AuthStateCacheQuery) FirstIDX(ctx context.Context) string {
	id, err := ascq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AuthStateCache entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one AuthStateCache entity is not found.
// Returns a *NotFoundError when no AuthStateCache entities are found.
func (ascq *AuthStateCacheQuery) Only(ctx context.Context) (*AuthStateCache, error) {
	nodes, err := ascq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{authstatecache.Label}
	default:
		return nil, &NotSingularError{authstatecache.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ascq *AuthStateCacheQuery) OnlyX(ctx context.Context) *AuthStateCache {
	node, err := ascq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AuthStateCache ID in the query.
// Returns a *NotSingularError when exactly one AuthStateCache ID is not found.
// Returns a *NotFoundError when no entities are found.
func (ascq *AuthStateCacheQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = ascq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{authstatecache.Label}
	default:
		err = &NotSingularError{authstatecache.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ascq *AuthStateCacheQuery) OnlyIDX(ctx context.Context) string {
	id, err := ascq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AuthStateCaches.
func (ascq *AuthStateCacheQuery) All(ctx context.Context) ([]*AuthStateCache, error) {
	if err := ascq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return ascq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (ascq *AuthStateCacheQuery) AllX(ctx context.Context) []*AuthStateCache {
	nodes, err := ascq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AuthStateCache IDs.
func (ascq *AuthStateCacheQuery) IDs(ctx context.Context) ([]string, error) {
	var ids []string
	if err := ascq.Select(authstatecache.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ascq *AuthStateCacheQuery) IDsX(ctx context.Context) []string {
	ids, err := ascq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ascq *AuthStateCacheQuery) Count(ctx context.Context) (int, error) {
	if err := ascq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return ascq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (ascq *AuthStateCacheQuery) CountX(ctx context.Context) int {
	count, err := ascq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ascq *AuthStateCacheQuery) Exist(ctx context.Context) (bool, error) {
	if err := ascq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return ascq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (ascq *AuthStateCacheQuery) ExistX(ctx context.Context) bool {
	exist, err := ascq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AuthStateCacheQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ascq *AuthStateCacheQuery) Clone() *AuthStateCacheQuery {
	if ascq == nil {
		return nil
	}
	return &AuthStateCacheQuery{
		config:     ascq.config,
		limit:      ascq.limit,
		offset:     ascq.offset,
		order:      append([]OrderFunc{}, ascq.order...),
		predicates: append([]predicate.AuthStateCache{}, ascq.predicates...),
		// clone intermediate query.
		sql:  ascq.sql.Clone(),
		path: ascq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ExpiresAt int64 `json:"expires_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AuthStateCache.Query().
//		GroupBy(authstatecache.FieldExpiresAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (ascq *AuthStateCacheQuery) GroupBy(field string, fields ...string) *AuthStateCacheGroupBy {
	group := &AuthStateCacheGroupBy{config: ascq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := ascq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return ascq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ExpiresAt int64 `json:"expires_at,omitempty"`
//	}
//
//	client.AuthStateCache.Query().
//		Select(authstatecache.FieldExpiresAt).
//		Scan(ctx, &v)
//
func (ascq *AuthStateCacheQuery) Select(fields ...string) *AuthStateCacheSelect {
	ascq.fields = append(ascq.fields, fields...)
	return &AuthStateCacheSelect{AuthStateCacheQuery: ascq}
}

func (ascq *AuthStateCacheQuery) prepareQuery(ctx context.Context) error {
	for _, f := range ascq.fields {
		if !authstatecache.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ascq.path != nil {
		prev, err := ascq.path(ctx)
		if err != nil {
			return err
		}
		ascq.sql = prev
	}
	return nil
}

func (ascq *AuthStateCacheQuery) sqlAll(ctx context.Context) ([]*AuthStateCache, error) {
	var (
		nodes = []*AuthStateCache{}
		_spec = ascq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &AuthStateCache{config: ascq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, ascq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ascq *AuthStateCacheQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ascq.querySpec()
	return sqlgraph.CountNodes(ctx, ascq.driver, _spec)
}

func (ascq *AuthStateCacheQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := ascq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (ascq *AuthStateCacheQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   authstatecache.Table,
			Columns: authstatecache.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: authstatecache.FieldID,
			},
		},
		From:   ascq.sql,
		Unique: true,
	}
	if unique := ascq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := ascq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, authstatecache.FieldID)
		for i := range fields {
			if fields[i] != authstatecache.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ascq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ascq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ascq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ascq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ascq *AuthStateCacheQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ascq.driver.Dialect())
	t1 := builder.Table(authstatecache.Table)
	columns := ascq.fields
	if len(columns) == 0 {
		columns = authstatecache.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ascq.sql != nil {
		selector = ascq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range ascq.predicates {
		p(selector)
	}
	for _, p := range ascq.order {
		p(selector)
	}
	if offset := ascq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ascq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AuthStateCacheGroupBy is the group-by builder for AuthStateCache entities.
type AuthStateCacheGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ascgb *AuthStateCacheGroupBy) Aggregate(fns ...AggregateFunc) *AuthStateCacheGroupBy {
	ascgb.fns = append(ascgb.fns, fns...)
	return ascgb
}

// Scan applies the group-by query and scans the result into the given value.
func (ascgb *AuthStateCacheGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := ascgb.path(ctx)
	if err != nil {
		return err
	}
	ascgb.sql = query
	return ascgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ascgb *AuthStateCacheGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := ascgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (ascgb *AuthStateCacheGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(ascgb.fields) > 1 {
		return nil, errors.New("ent: AuthStateCacheGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := ascgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ascgb *AuthStateCacheGroupBy) StringsX(ctx context.Context) []string {
	v, err := ascgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ascgb *AuthStateCacheGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ascgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{authstatecache.Label}
	default:
		err = fmt.Errorf("ent: AuthStateCacheGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ascgb *AuthStateCacheGroupBy) StringX(ctx context.Context) string {
	v, err := ascgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (ascgb *AuthStateCacheGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(ascgb.fields) > 1 {
		return nil, errors.New("ent: AuthStateCacheGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := ascgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ascgb *AuthStateCacheGroupBy) IntsX(ctx context.Context) []int {
	v, err := ascgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ascgb *AuthStateCacheGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ascgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{authstatecache.Label}
	default:
		err = fmt.Errorf("ent: AuthStateCacheGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ascgb *AuthStateCacheGroupBy) IntX(ctx context.Context) int {
	v, err := ascgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (ascgb *AuthStateCacheGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(ascgb.fields) > 1 {
		return nil, errors.New("ent: AuthStateCacheGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := ascgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ascgb *AuthStateCacheGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := ascgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ascgb *AuthStateCacheGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ascgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{authstatecache.Label}
	default:
		err = fmt.Errorf("ent: AuthStateCacheGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ascgb *AuthStateCacheGroupBy) Float64X(ctx context.Context) float64 {
	v, err := ascgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (ascgb *AuthStateCacheGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(ascgb.fields) > 1 {
		return nil, errors.New("ent: AuthStateCacheGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := ascgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ascgb *AuthStateCacheGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := ascgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ascgb *AuthStateCacheGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ascgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{authstatecache.Label}
	default:
		err = fmt.Errorf("ent: AuthStateCacheGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ascgb *AuthStateCacheGroupBy) BoolX(ctx context.Context) bool {
	v, err := ascgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ascgb *AuthStateCacheGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range ascgb.fields {
		if !authstatecache.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := ascgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ascgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ascgb *AuthStateCacheGroupBy) sqlQuery() *sql.Selector {
	selector := ascgb.sql.Select()
	aggregation := make([]string, 0, len(ascgb.fns))
	for _, fn := range ascgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(ascgb.fields)+len(ascgb.fns))
		for _, f := range ascgb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(ascgb.fields...)...)
}

// AuthStateCacheSelect is the builder for selecting fields of AuthStateCache entities.
type AuthStateCacheSelect struct {
	*AuthStateCacheQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (ascs *AuthStateCacheSelect) Scan(ctx context.Context, v interface{}) error {
	if err := ascs.prepareQuery(ctx); err != nil {
		return err
	}
	ascs.sql = ascs.AuthStateCacheQuery.sqlQuery(ctx)
	return ascs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ascs *AuthStateCacheSelect) ScanX(ctx context.Context, v interface{}) {
	if err := ascs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (ascs *AuthStateCacheSelect) Strings(ctx context.Context) ([]string, error) {
	if len(ascs.fields) > 1 {
		return nil, errors.New("ent: AuthStateCacheSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := ascs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ascs *AuthStateCacheSelect) StringsX(ctx context.Context) []string {
	v, err := ascs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (ascs *AuthStateCacheSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ascs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{authstatecache.Label}
	default:
		err = fmt.Errorf("ent: AuthStateCacheSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ascs *AuthStateCacheSelect) StringX(ctx context.Context) string {
	v, err := ascs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (ascs *AuthStateCacheSelect) Ints(ctx context.Context) ([]int, error) {
	if len(ascs.fields) > 1 {
		return nil, errors.New("ent: AuthStateCacheSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := ascs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ascs *AuthStateCacheSelect) IntsX(ctx context.Context) []int {
	v, err := ascs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (ascs *AuthStateCacheSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ascs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{authstatecache.Label}
	default:
		err = fmt.Errorf("ent: AuthStateCacheSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ascs *AuthStateCacheSelect) IntX(ctx context.Context) int {
	v, err := ascs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (ascs *AuthStateCacheSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(ascs.fields) > 1 {
		return nil, errors.New("ent: AuthStateCacheSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := ascs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ascs *AuthStateCacheSelect) Float64sX(ctx context.Context) []float64 {
	v, err := ascs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (ascs *AuthStateCacheSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ascs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{authstatecache.Label}
	default:
		err = fmt.Errorf("ent: AuthStateCacheSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ascs *AuthStateCacheSelect) Float64X(ctx context.Context) float64 {
	v, err := ascs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (ascs *AuthStateCacheSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(ascs.fields) > 1 {
		return nil, errors.New("ent: AuthStateCacheSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := ascs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ascs *AuthStateCacheSelect) BoolsX(ctx context.Context) []bool {
	v, err := ascs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (ascs *AuthStateCacheSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ascs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{authstatecache.Label}
	default:
		err = fmt.Errorf("ent: AuthStateCacheSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ascs *AuthStateCacheSelect) BoolX(ctx context.Context) bool {
	v, err := ascs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ascs *AuthStateCacheSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ascs.sql.Query()
	if err := ascs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
