// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/m-mizutani/octovy/pkg/infra/ent/checkrule"
	"github.com/m-mizutani/octovy/pkg/infra/ent/predicate"
)

// CheckRuleDelete is the builder for deleting a CheckRule entity.
type CheckRuleDelete struct {
	config
	hooks    []Hook
	mutation *CheckRuleMutation
}

// Where appends a list predicates to the CheckRuleDelete builder.
func (crd *CheckRuleDelete) Where(ps ...predicate.CheckRule) *CheckRuleDelete {
	crd.mutation.Where(ps...)
	return crd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (crd *CheckRuleDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(crd.hooks) == 0 {
		affected, err = crd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CheckRuleMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			crd.mutation = mutation
			affected, err = crd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(crd.hooks) - 1; i >= 0; i-- {
			if crd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = crd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, crd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (crd *CheckRuleDelete) ExecX(ctx context.Context) int {
	n, err := crd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (crd *CheckRuleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: checkrule.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: checkrule.FieldID,
			},
		},
	}
	if ps := crd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, crd.driver, _spec)
}

// CheckRuleDeleteOne is the builder for deleting a single CheckRule entity.
type CheckRuleDeleteOne struct {
	crd *CheckRuleDelete
}

// Exec executes the deletion query.
func (crdo *CheckRuleDeleteOne) Exec(ctx context.Context) error {
	n, err := crdo.crd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{checkrule.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (crdo *CheckRuleDeleteOne) ExecX(ctx context.Context) {
	crdo.crd.ExecX(ctx)
}
