// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/m-mizutani/octovy/pkg/infra/ent/predicate"
	"github.com/m-mizutani/octovy/pkg/infra/ent/repolabel"
	"github.com/m-mizutani/octovy/pkg/infra/ent/repository"
)

// RepoLabelQuery is the builder for querying RepoLabel entities.
type RepoLabelQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.RepoLabel
	// eager-loading edges.
	withRepos *RepositoryQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RepoLabelQuery builder.
func (rlq *RepoLabelQuery) Where(ps ...predicate.RepoLabel) *RepoLabelQuery {
	rlq.predicates = append(rlq.predicates, ps...)
	return rlq
}

// Limit adds a limit step to the query.
func (rlq *RepoLabelQuery) Limit(limit int) *RepoLabelQuery {
	rlq.limit = &limit
	return rlq
}

// Offset adds an offset step to the query.
func (rlq *RepoLabelQuery) Offset(offset int) *RepoLabelQuery {
	rlq.offset = &offset
	return rlq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rlq *RepoLabelQuery) Unique(unique bool) *RepoLabelQuery {
	rlq.unique = &unique
	return rlq
}

// Order adds an order step to the query.
func (rlq *RepoLabelQuery) Order(o ...OrderFunc) *RepoLabelQuery {
	rlq.order = append(rlq.order, o...)
	return rlq
}

// QueryRepos chains the current query on the "repos" edge.
func (rlq *RepoLabelQuery) QueryRepos() *RepositoryQuery {
	query := &RepositoryQuery{config: rlq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rlq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rlq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(repolabel.Table, repolabel.FieldID, selector),
			sqlgraph.To(repository.Table, repository.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, repolabel.ReposTable, repolabel.ReposPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(rlq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first RepoLabel entity from the query.
// Returns a *NotFoundError when no RepoLabel was found.
func (rlq *RepoLabelQuery) First(ctx context.Context) (*RepoLabel, error) {
	nodes, err := rlq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{repolabel.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rlq *RepoLabelQuery) FirstX(ctx context.Context) *RepoLabel {
	node, err := rlq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RepoLabel ID from the query.
// Returns a *NotFoundError when no RepoLabel ID was found.
func (rlq *RepoLabelQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rlq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{repolabel.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rlq *RepoLabelQuery) FirstIDX(ctx context.Context) int {
	id, err := rlq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RepoLabel entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one RepoLabel entity is not found.
// Returns a *NotFoundError when no RepoLabel entities are found.
func (rlq *RepoLabelQuery) Only(ctx context.Context) (*RepoLabel, error) {
	nodes, err := rlq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{repolabel.Label}
	default:
		return nil, &NotSingularError{repolabel.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rlq *RepoLabelQuery) OnlyX(ctx context.Context) *RepoLabel {
	node, err := rlq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RepoLabel ID in the query.
// Returns a *NotSingularError when exactly one RepoLabel ID is not found.
// Returns a *NotFoundError when no entities are found.
func (rlq *RepoLabelQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rlq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{repolabel.Label}
	default:
		err = &NotSingularError{repolabel.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rlq *RepoLabelQuery) OnlyIDX(ctx context.Context) int {
	id, err := rlq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RepoLabels.
func (rlq *RepoLabelQuery) All(ctx context.Context) ([]*RepoLabel, error) {
	if err := rlq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return rlq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (rlq *RepoLabelQuery) AllX(ctx context.Context) []*RepoLabel {
	nodes, err := rlq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RepoLabel IDs.
func (rlq *RepoLabelQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := rlq.Select(repolabel.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rlq *RepoLabelQuery) IDsX(ctx context.Context) []int {
	ids, err := rlq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rlq *RepoLabelQuery) Count(ctx context.Context) (int, error) {
	if err := rlq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return rlq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (rlq *RepoLabelQuery) CountX(ctx context.Context) int {
	count, err := rlq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rlq *RepoLabelQuery) Exist(ctx context.Context) (bool, error) {
	if err := rlq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return rlq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (rlq *RepoLabelQuery) ExistX(ctx context.Context) bool {
	exist, err := rlq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RepoLabelQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rlq *RepoLabelQuery) Clone() *RepoLabelQuery {
	if rlq == nil {
		return nil
	}
	return &RepoLabelQuery{
		config:     rlq.config,
		limit:      rlq.limit,
		offset:     rlq.offset,
		order:      append([]OrderFunc{}, rlq.order...),
		predicates: append([]predicate.RepoLabel{}, rlq.predicates...),
		withRepos:  rlq.withRepos.Clone(),
		// clone intermediate query.
		sql:  rlq.sql.Clone(),
		path: rlq.path,
	}
}

// WithRepos tells the query-builder to eager-load the nodes that are connected to
// the "repos" edge. The optional arguments are used to configure the query builder of the edge.
func (rlq *RepoLabelQuery) WithRepos(opts ...func(*RepositoryQuery)) *RepoLabelQuery {
	query := &RepositoryQuery{config: rlq.config}
	for _, opt := range opts {
		opt(query)
	}
	rlq.withRepos = query
	return rlq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RepoLabel.Query().
//		GroupBy(repolabel.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (rlq *RepoLabelQuery) GroupBy(field string, fields ...string) *RepoLabelGroupBy {
	group := &RepoLabelGroupBy{config: rlq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := rlq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return rlq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.RepoLabel.Query().
//		Select(repolabel.FieldName).
//		Scan(ctx, &v)
//
func (rlq *RepoLabelQuery) Select(fields ...string) *RepoLabelSelect {
	rlq.fields = append(rlq.fields, fields...)
	return &RepoLabelSelect{RepoLabelQuery: rlq}
}

func (rlq *RepoLabelQuery) prepareQuery(ctx context.Context) error {
	for _, f := range rlq.fields {
		if !repolabel.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rlq.path != nil {
		prev, err := rlq.path(ctx)
		if err != nil {
			return err
		}
		rlq.sql = prev
	}
	return nil
}

func (rlq *RepoLabelQuery) sqlAll(ctx context.Context) ([]*RepoLabel, error) {
	var (
		nodes       = []*RepoLabel{}
		_spec       = rlq.querySpec()
		loadedTypes = [1]bool{
			rlq.withRepos != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &RepoLabel{config: rlq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, rlq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := rlq.withRepos; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		ids := make(map[int]*RepoLabel, len(nodes))
		for _, node := range nodes {
			ids[node.ID] = node
			fks = append(fks, node.ID)
			node.Edges.Repos = []*Repository{}
		}
		var (
			edgeids []int
			edges   = make(map[int][]*RepoLabel)
		)
		_spec := &sqlgraph.EdgeQuerySpec{
			Edge: &sqlgraph.EdgeSpec{
				Inverse: true,
				Table:   repolabel.ReposTable,
				Columns: repolabel.ReposPrimaryKey,
			},
			Predicate: func(s *sql.Selector) {
				s.Where(sql.InValues(repolabel.ReposPrimaryKey[1], fks...))
			},
			ScanValues: func() [2]interface{} {
				return [2]interface{}{new(sql.NullInt64), new(sql.NullInt64)}
			},
			Assign: func(out, in interface{}) error {
				eout, ok := out.(*sql.NullInt64)
				if !ok || eout == nil {
					return fmt.Errorf("unexpected id value for edge-out")
				}
				ein, ok := in.(*sql.NullInt64)
				if !ok || ein == nil {
					return fmt.Errorf("unexpected id value for edge-in")
				}
				outValue := int(eout.Int64)
				inValue := int(ein.Int64)
				node, ok := ids[outValue]
				if !ok {
					return fmt.Errorf("unexpected node id in edges: %v", outValue)
				}
				if _, ok := edges[inValue]; !ok {
					edgeids = append(edgeids, inValue)
				}
				edges[inValue] = append(edges[inValue], node)
				return nil
			},
		}
		if err := sqlgraph.QueryEdges(ctx, rlq.driver, _spec); err != nil {
			return nil, fmt.Errorf(`query edges "repos": %w`, err)
		}
		query.Where(repository.IDIn(edgeids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := edges[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected "repos" node returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Repos = append(nodes[i].Edges.Repos, n)
			}
		}
	}

	return nodes, nil
}

func (rlq *RepoLabelQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rlq.querySpec()
	return sqlgraph.CountNodes(ctx, rlq.driver, _spec)
}

func (rlq *RepoLabelQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := rlq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (rlq *RepoLabelQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   repolabel.Table,
			Columns: repolabel.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: repolabel.FieldID,
			},
		},
		From:   rlq.sql,
		Unique: true,
	}
	if unique := rlq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := rlq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, repolabel.FieldID)
		for i := range fields {
			if fields[i] != repolabel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rlq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rlq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rlq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rlq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rlq *RepoLabelQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rlq.driver.Dialect())
	t1 := builder.Table(repolabel.Table)
	columns := rlq.fields
	if len(columns) == 0 {
		columns = repolabel.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rlq.sql != nil {
		selector = rlq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range rlq.predicates {
		p(selector)
	}
	for _, p := range rlq.order {
		p(selector)
	}
	if offset := rlq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rlq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RepoLabelGroupBy is the group-by builder for RepoLabel entities.
type RepoLabelGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rlgb *RepoLabelGroupBy) Aggregate(fns ...AggregateFunc) *RepoLabelGroupBy {
	rlgb.fns = append(rlgb.fns, fns...)
	return rlgb
}

// Scan applies the group-by query and scans the result into the given value.
func (rlgb *RepoLabelGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := rlgb.path(ctx)
	if err != nil {
		return err
	}
	rlgb.sql = query
	return rlgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (rlgb *RepoLabelGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := rlgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (rlgb *RepoLabelGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(rlgb.fields) > 1 {
		return nil, errors.New("ent: RepoLabelGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := rlgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (rlgb *RepoLabelGroupBy) StringsX(ctx context.Context) []string {
	v, err := rlgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (rlgb *RepoLabelGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = rlgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{repolabel.Label}
	default:
		err = fmt.Errorf("ent: RepoLabelGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (rlgb *RepoLabelGroupBy) StringX(ctx context.Context) string {
	v, err := rlgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (rlgb *RepoLabelGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(rlgb.fields) > 1 {
		return nil, errors.New("ent: RepoLabelGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := rlgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (rlgb *RepoLabelGroupBy) IntsX(ctx context.Context) []int {
	v, err := rlgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (rlgb *RepoLabelGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = rlgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{repolabel.Label}
	default:
		err = fmt.Errorf("ent: RepoLabelGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (rlgb *RepoLabelGroupBy) IntX(ctx context.Context) int {
	v, err := rlgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (rlgb *RepoLabelGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(rlgb.fields) > 1 {
		return nil, errors.New("ent: RepoLabelGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := rlgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (rlgb *RepoLabelGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := rlgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (rlgb *RepoLabelGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = rlgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{repolabel.Label}
	default:
		err = fmt.Errorf("ent: RepoLabelGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (rlgb *RepoLabelGroupBy) Float64X(ctx context.Context) float64 {
	v, err := rlgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (rlgb *RepoLabelGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(rlgb.fields) > 1 {
		return nil, errors.New("ent: RepoLabelGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := rlgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (rlgb *RepoLabelGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := rlgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (rlgb *RepoLabelGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = rlgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{repolabel.Label}
	default:
		err = fmt.Errorf("ent: RepoLabelGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (rlgb *RepoLabelGroupBy) BoolX(ctx context.Context) bool {
	v, err := rlgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (rlgb *RepoLabelGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range rlgb.fields {
		if !repolabel.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := rlgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rlgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (rlgb *RepoLabelGroupBy) sqlQuery() *sql.Selector {
	selector := rlgb.sql.Select()
	aggregation := make([]string, 0, len(rlgb.fns))
	for _, fn := range rlgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(rlgb.fields)+len(rlgb.fns))
		for _, f := range rlgb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(rlgb.fields...)...)
}

// RepoLabelSelect is the builder for selecting fields of RepoLabel entities.
type RepoLabelSelect struct {
	*RepoLabelQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (rls *RepoLabelSelect) Scan(ctx context.Context, v interface{}) error {
	if err := rls.prepareQuery(ctx); err != nil {
		return err
	}
	rls.sql = rls.RepoLabelQuery.sqlQuery(ctx)
	return rls.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (rls *RepoLabelSelect) ScanX(ctx context.Context, v interface{}) {
	if err := rls.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (rls *RepoLabelSelect) Strings(ctx context.Context) ([]string, error) {
	if len(rls.fields) > 1 {
		return nil, errors.New("ent: RepoLabelSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := rls.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (rls *RepoLabelSelect) StringsX(ctx context.Context) []string {
	v, err := rls.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (rls *RepoLabelSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = rls.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{repolabel.Label}
	default:
		err = fmt.Errorf("ent: RepoLabelSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (rls *RepoLabelSelect) StringX(ctx context.Context) string {
	v, err := rls.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (rls *RepoLabelSelect) Ints(ctx context.Context) ([]int, error) {
	if len(rls.fields) > 1 {
		return nil, errors.New("ent: RepoLabelSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := rls.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (rls *RepoLabelSelect) IntsX(ctx context.Context) []int {
	v, err := rls.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (rls *RepoLabelSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = rls.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{repolabel.Label}
	default:
		err = fmt.Errorf("ent: RepoLabelSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (rls *RepoLabelSelect) IntX(ctx context.Context) int {
	v, err := rls.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (rls *RepoLabelSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(rls.fields) > 1 {
		return nil, errors.New("ent: RepoLabelSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := rls.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (rls *RepoLabelSelect) Float64sX(ctx context.Context) []float64 {
	v, err := rls.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (rls *RepoLabelSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = rls.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{repolabel.Label}
	default:
		err = fmt.Errorf("ent: RepoLabelSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (rls *RepoLabelSelect) Float64X(ctx context.Context) float64 {
	v, err := rls.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (rls *RepoLabelSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(rls.fields) > 1 {
		return nil, errors.New("ent: RepoLabelSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := rls.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (rls *RepoLabelSelect) BoolsX(ctx context.Context) []bool {
	v, err := rls.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (rls *RepoLabelSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = rls.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{repolabel.Label}
	default:
		err = fmt.Errorf("ent: RepoLabelSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (rls *RepoLabelSelect) BoolX(ctx context.Context) bool {
	v, err := rls.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (rls *RepoLabelSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := rls.sql.Query()
	if err := rls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
