// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/m-mizutani/octovy/pkg/infra/ent/predicate"
	"github.com/m-mizutani/octovy/pkg/infra/ent/vulnstatusindex"
)

// VulnStatusIndexDelete is the builder for deleting a VulnStatusIndex entity.
type VulnStatusIndexDelete struct {
	config
	hooks    []Hook
	mutation *VulnStatusIndexMutation
}

// Where appends a list predicates to the VulnStatusIndexDelete builder.
func (vsid *VulnStatusIndexDelete) Where(ps ...predicate.VulnStatusIndex) *VulnStatusIndexDelete {
	vsid.mutation.Where(ps...)
	return vsid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (vsid *VulnStatusIndexDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(vsid.hooks) == 0 {
		affected, err = vsid.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*VulnStatusIndexMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			vsid.mutation = mutation
			affected, err = vsid.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(vsid.hooks) - 1; i >= 0; i-- {
			if vsid.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = vsid.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, vsid.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (vsid *VulnStatusIndexDelete) ExecX(ctx context.Context) int {
	n, err := vsid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (vsid *VulnStatusIndexDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: vulnstatusindex.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: vulnstatusindex.FieldID,
			},
		},
	}
	if ps := vsid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, vsid.driver, _spec)
}

// VulnStatusIndexDeleteOne is the builder for deleting a single VulnStatusIndex entity.
type VulnStatusIndexDeleteOne struct {
	vsid *VulnStatusIndexDelete
}

// Exec executes the deletion query.
func (vsido *VulnStatusIndexDeleteOne) Exec(ctx context.Context) error {
	n, err := vsido.vsid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{vulnstatusindex.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (vsido *VulnStatusIndexDeleteOne) ExecX(ctx context.Context) {
	vsido.vsid.ExecX(ctx)
}
