// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/m-mizutani/octovy/pkg/infra/ent/predicate"
	"github.com/m-mizutani/octovy/pkg/infra/ent/vulnstatus"
)

// VulnStatusDelete is the builder for deleting a VulnStatus entity.
type VulnStatusDelete struct {
	config
	hooks    []Hook
	mutation *VulnStatusMutation
}

// Where appends a list predicates to the VulnStatusDelete builder.
func (vsd *VulnStatusDelete) Where(ps ...predicate.VulnStatus) *VulnStatusDelete {
	vsd.mutation.Where(ps...)
	return vsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (vsd *VulnStatusDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(vsd.hooks) == 0 {
		affected, err = vsd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*VulnStatusMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			vsd.mutation = mutation
			affected, err = vsd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(vsd.hooks) - 1; i >= 0; i-- {
			if vsd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = vsd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, vsd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (vsd *VulnStatusDelete) ExecX(ctx context.Context) int {
	n, err := vsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (vsd *VulnStatusDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: vulnstatus.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: vulnstatus.FieldID,
			},
		},
	}
	if ps := vsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, vsd.driver, _spec)
}

// VulnStatusDeleteOne is the builder for deleting a single VulnStatus entity.
type VulnStatusDeleteOne struct {
	vsd *VulnStatusDelete
}

// Exec executes the deletion query.
func (vsdo *VulnStatusDeleteOne) Exec(ctx context.Context) error {
	n, err := vsdo.vsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{vulnstatus.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (vsdo *VulnStatusDeleteOne) ExecX(ctx context.Context) {
	vsdo.vsd.ExecX(ctx)
}
