// Code generated by entc, DO NOT EDIT.

package authstatecache

const (
	// Label holds the string label denoting the authstatecache type in the database.
	Label = "auth_state_cache"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// Table holds the table name of the authstatecache in the database.
	Table = "auth_state_caches"
)

// Columns holds all SQL columns for authstatecache fields.
var Columns = []string{
	FieldID,
	FieldExpiresAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
