// Code generated by entc, DO NOT EDIT.

package vulnstatus

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/m-mizutani/octovy/pkg/domain/types"
	"github.com/m-mizutani/octovy/pkg/infra/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSource), v))
	})
}

// PkgName applies equality check predicate on the "pkg_name" field. It's identical to PkgNameEQ.
func PkgName(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPkgName), v))
	})
}

// VulnID applies equality check predicate on the "vuln_id" field. It's identical to VulnIDEQ.
func VulnID(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldVulnID), v))
	})
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v int64) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldExpiresAt), v))
	})
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v int64) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// Comment applies equality check predicate on the "comment" field. It's identical to CommentEQ.
func Comment(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldComment), v))
	})
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v types.VulnStatusType) predicate.VulnStatus {
	vc := v
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStatus), vc))
	})
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v types.VulnStatusType) predicate.VulnStatus {
	vc := v
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldStatus), vc))
	})
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...types.VulnStatusType) predicate.VulnStatus {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.VulnStatus(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldStatus), v...))
	})
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...types.VulnStatusType) predicate.VulnStatus {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.VulnStatus(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldStatus), v...))
	})
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSource), v))
	})
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldSource), v))
	})
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.VulnStatus {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.VulnStatus(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldSource), v...))
	})
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.VulnStatus {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.VulnStatus(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldSource), v...))
	})
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldSource), v))
	})
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldSource), v))
	})
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldSource), v))
	})
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldSource), v))
	})
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldSource), v))
	})
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldSource), v))
	})
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldSource), v))
	})
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldSource), v))
	})
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldSource), v))
	})
}

// PkgNameEQ applies the EQ predicate on the "pkg_name" field.
func PkgNameEQ(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPkgName), v))
	})
}

// PkgNameNEQ applies the NEQ predicate on the "pkg_name" field.
func PkgNameNEQ(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldPkgName), v))
	})
}

// PkgNameIn applies the In predicate on the "pkg_name" field.
func PkgNameIn(vs ...string) predicate.VulnStatus {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.VulnStatus(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldPkgName), v...))
	})
}

// PkgNameNotIn applies the NotIn predicate on the "pkg_name" field.
func PkgNameNotIn(vs ...string) predicate.VulnStatus {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.VulnStatus(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldPkgName), v...))
	})
}

// PkgNameGT applies the GT predicate on the "pkg_name" field.
func PkgNameGT(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldPkgName), v))
	})
}

// PkgNameGTE applies the GTE predicate on the "pkg_name" field.
func PkgNameGTE(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldPkgName), v))
	})
}

// PkgNameLT applies the LT predicate on the "pkg_name" field.
func PkgNameLT(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldPkgName), v))
	})
}

// PkgNameLTE applies the LTE predicate on the "pkg_name" field.
func PkgNameLTE(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldPkgName), v))
	})
}

// PkgNameContains applies the Contains predicate on the "pkg_name" field.
func PkgNameContains(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldPkgName), v))
	})
}

// PkgNameHasPrefix applies the HasPrefix predicate on the "pkg_name" field.
func PkgNameHasPrefix(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldPkgName), v))
	})
}

// PkgNameHasSuffix applies the HasSuffix predicate on the "pkg_name" field.
func PkgNameHasSuffix(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldPkgName), v))
	})
}

// PkgNameEqualFold applies the EqualFold predicate on the "pkg_name" field.
func PkgNameEqualFold(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldPkgName), v))
	})
}

// PkgNameContainsFold applies the ContainsFold predicate on the "pkg_name" field.
func PkgNameContainsFold(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldPkgName), v))
	})
}

// PkgTypeEQ applies the EQ predicate on the "pkg_type" field.
func PkgTypeEQ(v types.PkgType) predicate.VulnStatus {
	vc := v
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPkgType), vc))
	})
}

// PkgTypeNEQ applies the NEQ predicate on the "pkg_type" field.
func PkgTypeNEQ(v types.PkgType) predicate.VulnStatus {
	vc := v
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldPkgType), vc))
	})
}

// PkgTypeIn applies the In predicate on the "pkg_type" field.
func PkgTypeIn(vs ...types.PkgType) predicate.VulnStatus {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.VulnStatus(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldPkgType), v...))
	})
}

// PkgTypeNotIn applies the NotIn predicate on the "pkg_type" field.
func PkgTypeNotIn(vs ...types.PkgType) predicate.VulnStatus {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.VulnStatus(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldPkgType), v...))
	})
}

// VulnIDEQ applies the EQ predicate on the "vuln_id" field.
func VulnIDEQ(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldVulnID), v))
	})
}

// VulnIDNEQ applies the NEQ predicate on the "vuln_id" field.
func VulnIDNEQ(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldVulnID), v))
	})
}

// VulnIDIn applies the In predicate on the "vuln_id" field.
func VulnIDIn(vs ...string) predicate.VulnStatus {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.VulnStatus(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldVulnID), v...))
	})
}

// VulnIDNotIn applies the NotIn predicate on the "vuln_id" field.
func VulnIDNotIn(vs ...string) predicate.VulnStatus {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.VulnStatus(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldVulnID), v...))
	})
}

// VulnIDGT applies the GT predicate on the "vuln_id" field.
func VulnIDGT(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldVulnID), v))
	})
}

// VulnIDGTE applies the GTE predicate on the "vuln_id" field.
func VulnIDGTE(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldVulnID), v))
	})
}

// VulnIDLT applies the LT predicate on the "vuln_id" field.
func VulnIDLT(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldVulnID), v))
	})
}

// VulnIDLTE applies the LTE predicate on the "vuln_id" field.
func VulnIDLTE(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldVulnID), v))
	})
}

// VulnIDContains applies the Contains predicate on the "vuln_id" field.
func VulnIDContains(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldVulnID), v))
	})
}

// VulnIDHasPrefix applies the HasPrefix predicate on the "vuln_id" field.
func VulnIDHasPrefix(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldVulnID), v))
	})
}

// VulnIDHasSuffix applies the HasSuffix predicate on the "vuln_id" field.
func VulnIDHasSuffix(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldVulnID), v))
	})
}

// VulnIDEqualFold applies the EqualFold predicate on the "vuln_id" field.
func VulnIDEqualFold(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldVulnID), v))
	})
}

// VulnIDContainsFold applies the ContainsFold predicate on the "vuln_id" field.
func VulnIDContainsFold(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldVulnID), v))
	})
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v int64) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldExpiresAt), v))
	})
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v int64) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldExpiresAt), v))
	})
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...int64) predicate.VulnStatus {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.VulnStatus(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldExpiresAt), v...))
	})
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...int64) predicate.VulnStatus {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.VulnStatus(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldExpiresAt), v...))
	})
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v int64) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldExpiresAt), v))
	})
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v int64) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldExpiresAt), v))
	})
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v int64) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldExpiresAt), v))
	})
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v int64) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldExpiresAt), v))
	})
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v int64) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v int64) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...int64) predicate.VulnStatus {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.VulnStatus(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...int64) predicate.VulnStatus {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.VulnStatus(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v int64) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v int64) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v int64) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v int64) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCreatedAt), v))
	})
}

// CommentEQ applies the EQ predicate on the "comment" field.
func CommentEQ(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldComment), v))
	})
}

// CommentNEQ applies the NEQ predicate on the "comment" field.
func CommentNEQ(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldComment), v))
	})
}

// CommentIn applies the In predicate on the "comment" field.
func CommentIn(vs ...string) predicate.VulnStatus {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.VulnStatus(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldComment), v...))
	})
}

// CommentNotIn applies the NotIn predicate on the "comment" field.
func CommentNotIn(vs ...string) predicate.VulnStatus {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.VulnStatus(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldComment), v...))
	})
}

// CommentGT applies the GT predicate on the "comment" field.
func CommentGT(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldComment), v))
	})
}

// CommentGTE applies the GTE predicate on the "comment" field.
func CommentGTE(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldComment), v))
	})
}

// CommentLT applies the LT predicate on the "comment" field.
func CommentLT(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldComment), v))
	})
}

// CommentLTE applies the LTE predicate on the "comment" field.
func CommentLTE(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldComment), v))
	})
}

// CommentContains applies the Contains predicate on the "comment" field.
func CommentContains(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldComment), v))
	})
}

// CommentHasPrefix applies the HasPrefix predicate on the "comment" field.
func CommentHasPrefix(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldComment), v))
	})
}

// CommentHasSuffix applies the HasSuffix predicate on the "comment" field.
func CommentHasSuffix(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldComment), v))
	})
}

// CommentEqualFold applies the EqualFold predicate on the "comment" field.
func CommentEqualFold(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldComment), v))
	})
}

// CommentContainsFold applies the ContainsFold predicate on the "comment" field.
func CommentContainsFold(v string) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldComment), v))
	})
}

// HasAuthor applies the HasEdge predicate on the "author" edge.
func HasAuthor() predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(AuthorTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, AuthorTable, AuthorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAuthorWith applies the HasEdge predicate on the "author" edge with a given conditions (other predicates).
func HasAuthorWith(preds ...predicate.User) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(AuthorInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, AuthorTable, AuthorColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.VulnStatus) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.VulnStatus) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.VulnStatus) predicate.VulnStatus {
	return predicate.VulnStatus(func(s *sql.Selector) {
		p(s.Not())
	})
}
