// Code generated by entc, DO NOT EDIT.

package rule

const (
	// Label holds the string label denoting the rule type in the database.
	Label = "rule"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAction holds the string denoting the action field in the database.
	FieldAction = "action"
	// EdgeSeverity holds the string denoting the severity edge name in mutations.
	EdgeSeverity = "severity"
	// Table holds the table name of the rule in the database.
	Table = "rules"
	// SeverityTable is the table that holds the severity relation/edge.
	SeverityTable = "rules"
	// SeverityInverseTable is the table name for the Severity entity.
	// It exists in this package in order to avoid circular dependency with the "severity" package.
	SeverityInverseTable = "severities"
	// SeverityColumn is the table column denoting the severity relation/edge.
	SeverityColumn = "rule_severity"
)

// Columns holds all SQL columns for rule fields.
var Columns = []string{
	FieldID,
	FieldAction,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "rules"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"rule_severity",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}
