name: Build and deploy container image

on:
  push:
    branches:
      - main

permissions:
  id-token: write

env:
  TAG_NAME: octovy:${{ github.sha }}
  GCP_IMAGE_NAME: asia-northeast1-docker.pkg.dev/octovy-service/service-images/octovy:${{ github.sha }}
  GCP_PROJECT_ID: octovy-service
  SERVICE_ID: octovy
  CLOUD_RUN_REGION: asia-northeast1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker image
        run: docker build . -t ${{ env.TAG_NAME }}
      - name: Rename image
        run: docker tag ${{ env.TAG_NAME }} ${{ env.GCP_IMAGE_NAME }}
      - id: "auth"
        name: "Authenticate to GCP"
        uses: "google-github-actions/auth@v0.4.3"
        with:
          create_credentials_file: "true"
          workload_identity_provider: "projects/533751496677/locations/global/workloadIdentityPools/github-oidc-pool/providers/oidc-github-provider"
          service_account: "deployer@octovy-service.iam.gserviceaccount.com"
      - name: "Login gcloud"
        run: gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
      - name: Configure Docker
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev
      - name: Push image
        run: docker push ${{ env.GCP_IMAGE_NAME }}
      - uses: google-github-actions/setup-gcloud@master
      - run: gcloud components install beta
      - run: |
          gcloud beta run deploy "${SERVICE_ID}" \
            --project="${GCP_PROJECT_ID}" \
            --image "${GCP_IMAGE_NAME}" \
            --region="${CLOUD_RUN_REGION}" \
            --platform="managed" \
            --cpu=1  \
            --memory=512Mi \
            --port 9080 \
            --allow-unauthenticated \
            --ingress=all \
            --set-env-vars "OCTOVY_LOG_LEVEL=debug,
              OCTOVY_LOG_FORMAT=json,
              OCTOVY_FRONTEND_URL=https://octovy.dev,
              OCTOVY_GITHUB_APP_ID=109024,
              OCTOVY_GITHUB_CLIENT_ID=Iv1.6fbf414816a6e06b,
              OCTOVY_ADDR=0.0.0.0,
              OCTOVY_DB_TYPE=postgres,
              OCTOVY_TRIVY_DB_PATH=tmp/trivy.db,
              OCTOVY_OPA_URL=https://opa-server-h6tk4k5hyq-an.a.run.app,
              OCTOVY_OPA_PATH=ubie/octovy,
              OCTOVY_DISABLE_WEBHOOK_TRIVY=1,
              GIN_MODE=release" \
            --service-account="octovy-service@octovy-service.iam.gserviceaccount.com"

      # teardown
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "Deployed octovy server ${{ github.sha }}"
