name: Build and publish container image

on:
  push:

jobs:
  ghcr:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: octovy
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
  gcp:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: gcr.io/octovy/octovy:${{ github.sha }}
      GCP_PROJECT_ID: octovy
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1
      - name: GCP Authenticate
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
      - name: Configure Docker
        run: gcloud auth configure-docker --quiet
      - name: Build Docker image
        run: docker build . -t $IMAGE_NAME
      - name: Push Docker image
        run: docker push $IMAGE_NAME
