name: Build and publish container image

on:
  push:
env:
  TAG_NAME: octovy:${{ github.sha }}
  GITHUB_IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/octovy:${{ github.sha }}
  GCP_IMAGE_NAME: gcr.io/octovy/octovy:${{ github.sha }}

jobs:
  ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker image
        run: docker build . -t ${{ env.TAG_NAME }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Rename image
        run: docker tag ${{ env.TAG_NAME }} ${{ env.GITHUB_IMAGE_NAME }}
      - name: Push image
        run: docker push ${{ env.GITHUB_IMAGE_NAME }}

  gcp:
    runs-on: ubuntu-latest
    env:
      GCP_PROJECT_ID: octovy
      REGION: asia-northeast1
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - run: echo hoge | wc
      - name: GCP Authenticate
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker image
        run: docker build . -t ${{ env.GCP_IMAGE_NAME }}

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet
      - name: Push Docker image
        run: docker push ${{ env.GCP_IMAGE_NAME }}
