name: sqlc

on: [push]

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout upstream repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: sqlc-dev/setup-sqlc@v4
        with:
          sqlc-version: "1.21.0"
      - run: sqlc diff
