name: Unit test

on: [push]

jobs:
  testing:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: pguser
          POSTGRES_PASSWORD: pgpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout upstream repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
      - run: go run . migrate
        env:
          OCTOVY_DB_USER: pguser
          OCTOVY_DB_PASSWORD: pgpass
          OCTOVY_DB_NAME: testdb
      - run: go test --tags github ./...
        env:
          TEST_DB_DSN: "user=pguser password=pgpass dbname=testdb"
      - run: go vet --tags github ./...
